### ISSUE TITLE
Setup Travis CI for build AppImage (portable binary package for Linux)

### ISSUE THREAD

**Issue by Symbian9** [4v0v/4n1m#36]
Lets setup Travis CI for auto-build *AppImage* (portable package for Linux) for each commit:

- AppImage Docs - https://docs.appimage.org/

### TODO

0. [ ] Create `../blob/master/.travis.yml`
1. https://github.com/appimage/AppImageKit
1.1. https://github.com/probonopd/linuxdeployqt
1.2 https://github.com/linuxdeploy
2. https://github.com/probonopd/uploadtool
3. [ ] Enable Travis CI pushing to GitHub releases for this repo.

For example, take a look on *LeoCAD* `.travis.yml` implementation:

- https://github.com/leozide/leocad/blob/master/.travis.yml

And here is how resulted builds would look like:

- https://github.com/leozide/leocad/releases/tag/continuous

For any AppImage packaging questions & support:

- https://docs.appimage.org/user-guide/faq.html#question-where-do-i-get-support

**Comment by 4v0v** [comment]
Some stuff in the codesource is not linux friendly, also I've used but never initialized auto-build tools (and tbh my "priority" is to set it up for W10).
I'll look that up eventually. :)
